### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by sushmit1** [Fusion-OS/official_devices#1]
## Device you want to apply for
```
Redmi Y2/S2 (ysl)
```

## Device tree sources

```
https://github.com/sushmit1/device_xiaomi_ysl-S/tree/12
https://github.com/sushmit1/android_device_xiaomi_msm8953-common
https://github.com/sushmit1/kernel_xiaomi_ysl
https://github.com/sushmit1/android_vendor_xiaomi
```

## Number of ROM's you maintain officially
```
1
```

## Selinux Status
```
Enforcing
```

## Any Exceptions/special concern?
```
None
```

## Did you properly read Device requirements and Maintainer requirements before applying? What part of those requirements do you violate?
```
I have read read Device requirements and Maintainer requirements properly and I don't violate any.
```

### Telegram username
```
@uchihasushmit
```

### GitHub username
```
sushmit1
```

### XDA username
```
uchihasushmit
```

**Comment by sarthakroy2002** [comment]
@sushmit1 Okay you are accepted... Welcome to the Team :)

**Comment by kardebayan** [comment]
@sushmit1 Ohing

**Comment by ad1tyas1ngh** [comment]
@kardebayan
