### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Willylakshit** [Fusion-OS/official_devices#1]
## Device you want to apply for
```
Realme C3 
```

## Device tree sources

```
https://github.com/SuperiorOS-Devices/device_realme_RMX2020
https://github.com/SuperiorOS-Devices/kernel_realme_RMX2020
https://github.com/SuperiorOS-Devices/vendor_realme_RMX2020
```

## Number of ROM's you maintain officially
```
1
```

## Selinux Status
```
enforcing
```

## Any Exceptions/special concern?
```
No ig
```

## Did you properly read Device requirements and Maintainer requirements before applying? What part of those requirements do you violate?
```
No
```

### Telegram username
```
WillyS69
```

### GitHub username
```
Willylakshit
```

### XDA username
```
WillyS69
```

**Comment by sarthakroy2002** [comment]
Ping me up at TG (sarthakroy2002). You will be with me during RMX2020 releases.
