### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by prathamdby** [Fusion-OS/official_devices#2]
## Device you want to apply for
```
RM6785 (Realme 6/6i(Indian)/6s/7/Narzo/Narzo 20 Pro/Narzo 30 4G)
```

## Device tree sources

```
https://github.com/prathamdubey2005/device_realme_RM6785
https://github.com/prathamdubey2005/vendor_realme_RM6785
https://github.com/sarthakroy2002/kernel_realme_wasabi
```

## Number of ROM's you maintain officially
```
None
```

## Selinux Status
```
Enforcing
```

## Any Exceptions/special concern?
```
No
```

## Did you properly read Device requirements and Maintainer requirements before applying? What part of those requirements do you violate?
```
Yes I read all of them properly. I violate none of those requirements.
```

### Telegram username
```
PrathamWasTaken
```

### GitHub username
```
prathamdubey2005
```

### XDA username
```
None
```

**Comment by sarthakroy2002** [comment]
You are accepted! Ping me up at TG (sarthakroy2002).
