### ISSUE TITLE
New 🅱️aintainer

### ISSUE THREAD

**Issue by resist15** [Fusion-OS/official_devices#5]
## Device you want to apply for
```
Xiaomi POCO F1
```

## Device tree sources

```
https://github.com/resist15/android_device_xiaomi_beryllium
https://github.com/resist15/android_device_xiaomi_sdm845-common
https://github.com/PainKiller3/kernel_xiaomi_sdm845/tree/twelve
https://github.com/resist15/vendor_xiaomi
```

## Number of ROM's you maintain officially
```
1
```

## Selinux Status
```
Enforcing
```

## Any Exceptions/special concern?
```
No
```

## Did you properly read Device requirements and Maintainer requirements before applying? What part of those requirements do you violate?
```
ye
```

### Telegram username
```
@xyz_sourav
```

### GitHub username
```
resist15
```

### XDA username
```
snorlax77
```

**Comment by sarthakroy2002** [comment]
@resist15 +1 from my side... Seems fine... Waiting for approval from others....

**Comment by SparXFusion** [comment]
@resist15 You are approved! Pm @SakthivelNadar

**Comment by resist15** [comment]
nice thx

**Comment by sushmit1** [comment]
@resist15 Wew

**Comment by sajidshahriar72543** [comment]
Full maintainerbaazi
