### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by agam778** [Fusion-OS/official_devices#6]
## Device you want to apply for
```
Poco F3/Mi 11X/Redmi K40 (alioth)
```

## Device tree sources

```
# Device tree
https://github.com/cristianvaz/device_xiaomi_alioth
https://github.com/cristianvaz/vendor_xiaomi_sm8250-common

# Kernel
https://github.com/EmanuelCN/kernel_xiaomi_sm8250

# Vendor tree
https://github.com/cristianvaz/vendor_xiaomi_alioth
https://github.com/cristianvaz/vendor_xiaomi_sm8250-common
```

## Number of ROM's you maintain officially
```
N/A
```

## Selinux Status
```
Enforcing
```

## Any Exceptions/special concern?
```
No
```

## Did you properly read Device requirements and Maintainer requirements before applying? What part of those requirements do you violate?
```
Sadly, No contributions in device tree :(
```

### Telegram username
```
agam778
```

### GitHub username
```
agam778
```

### XDA username
```
agam778
```

**Comment by resist15** [comment]
Not Even Forked U Cant Expect Official Without even forking it

**Comment by agam778** [comment]
Well lol, I asked Sarthak for the same but he said to apply, so idk

**Comment by sarthakroy2002** [comment]
> Well lol, I asked Sarthak the same but he said to apply, so idk

i didnt expect that u wouldnt even fork trees and do bringup

**Comment by agam778** [comment]
> 
> 
> > Well lol, I asked Sarthak the same but he said to apply, so idk
> 
> i didnt expect that u wouldnt even fork trees and do bringup
> 

Ah lol, anyways I made my own trees and did bringup already

Will try to re apply later 👍
