### ISSUE TITLE
maintainer for rova

### ISSUE THREAD

**Issue by veshrao** [Fusion-OS/official_devices#7]
## Device you want to apply for
```
Redmi 4A (Rolex) + Redmi 5A (Riva) = Rova
```

## Device tree sources

```
https://github.com/veshrao/device_xiaomi_rova (fusion.s branch)
https://github.com/mi-msm8937/android_kernel_xiaomi_msm8937
https://github.com/veshrao/vendor_xiaomi_rova_main
```

## Number of ROM's you maintain officially
```
2 officially  (xdroid & styx)
```

## Selinux Status
```
enforcing
```

## Any Exceptions/special concern?
```
need 2 patches/commits in source for bluetooth & hotspot-wifi switching to work
```

## Did you properly read Device requirements and Maintainer requirements before applying? What part of those requirements do you violate?
```
yes.
```

### Telegram username
```
@veshrao
```

### GitHub username
```
veshrao
```

### XDA username
```
veshrao
```

**Comment by sushmit1** [comment]
Seems fine.

**Comment by sushmit1** [comment]
Share those patches

**Comment by veshrao** [comment]
> Share those patches

for bluetooth (https://github.com/AospExtended/platform_system_bt/commit/60c1afdd3005644ae5b52458c73bde75d9504e80)

for hotspot-wifi switching (https://github.com/ChuckProjekt/platform_hardware_qcom_wlan/commit/f99cb952c66fea7bbcf63e9288d842ec98c128db)

**Comment by kardebayan** [comment]
@veshrao about wifi-hotspot, You dont need that commit in source, instead pick this https://github.com/ArrowOS/android_hardware_interfaces/commit/b29e65efccca328e23e0dd7d3640cbb00d2b7d96 and drop that broken flag from your tree

**Comment by veshrao** [comment]
> @veshrao about wifi-hotspot, You dont need that commit in source, instead pick this [ArrowOS/android_hardware_interfaces@b29e65e](https://github.com/ArrowOS/android_hardware_interfaces/commit/b29e65efccca328e23e0dd7d3640cbb00d2b7d96) and drop that broken flag from your tree

noted/got it

**Comment by sarthakroy2002** [comment]
seems fine 

+1 from my side

**Comment by Dhruvgera** [comment]
This is so beautiful, it's like a mesmerizing sunset with daffodils in front of you, swaying with the wind as the sunshine bounces off the petals, glistening through the miniscule water droplets. Creating the best scenery these human eyes will ever see

**Comment by sarthakroy2002** [comment]
@veshrao ping up Sakthivel on TG
