### ISSUE TITLE
for rm10p - sweet maintainership

### ISSUE THREAD

**Issue by kangeraarav** [Fusion-OS/official_devices#9]
## Device you want to apply for
sweet {xiaomi}
Your device name
redmi note 10 pro

## Device tree sources
https://github.com/kangeraarav/device_xiaomi_sweet_2
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
https://github.com/kangeraarav/android-device-xiaomi-sm6150-common
https://github.com/vantoman/kernel_xiaomi_sm6150.git
https://github.com/sweet-sm6150/vendor_xiaomi

## Number of ROM's you maintain officially
```
Insert here
```
3
## Selinux Status
```
Insert here
enforcing

## Any Exceptions/special concern?
```
No
```

## Did you properly read Device requirements and Maintainer requirements before applying? What part of those requirements do you violate?
```
Insert here
yes

## Contact
on telegram
### Telegram username
@aarav_it_mattwrs
Your Telegram username
```

### GitHub username
```
Your GitHub username
``` kanger_aarav

### XDA username
```
Your XDA username
```no done yet

**Comment by sarthakroy2002** [comment]
https://github.com/kangeraarav/device_xiaomi_sweet_2/commit/ec15d0deda5f57a9e48a44aa80d594f177fa92e7

https://github.com/kangeraarav/device_xiaomi_sweet_2/commit/0dc9b82cf7eaf81069d9f05e6f5b87c647d4f246

https://github.com/kangeraarav/device_xiaomi_sweet_2/commit/6b081ec49cf937e483c11e2e3c6b3695e6af33a3

I dont think these are even accepted by any 'OFFICIAL' ROM. 

Improve yourself and Apply after 2 months :) Stay Safe and Enjoy Learning :)

**Comment by kangeraarav** [comment]
ooh ok sir thnx for telling me btw i had updated my trees can u check my pex trees??
